import dotenv from 'dotenv';
import Movie from './models/Post.js';
import connectDB from './libs/db.js';
import { encryptUrl } from './libs/crypto.js';

dotenv.config();

const sampleVideoLinks = {
  movie1: {
    '360p': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    '480p': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    '720p': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    '1080p': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoywatches.mp4',
    '4k': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
  },
  movie2: {
    '480p': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    '720p': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    '1080p': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    '4k': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
  },
  movie3: {
    '720p': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4',
    '1080p': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    '4k': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
  },
};

function encryptDownloadObject(obj) {
  if (!obj) return {};
  const res = {};
  for (const [key, val] of Object.entries(obj)) {
    res[key] = val ? encryptUrl(val) : '';
  }
  return res;
}

const mockMovies = [
  {
    title: 'Dune: Part Two',
    slug: 'dune-part-two-2024',
    bgposter: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1600&auto=format&fit=crop',
    smposter: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=600&auto=format&fit=crop',
    titlecategory: 'Movies',
    description: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
    rating: '8.6',
    duration: '2h 46m',
    year: '2024',
    genre: ['Action', 'Science_Fiction', 'Adventure'],
    language: 'English',
    subtitle: 'English / Bengali Subtitles',
    size: '2.8 GB',
    quality: '4K Ultra HD',
    youtubelink: 'https://www.youtube.com/watch?v=Way9Dexny3w',
    category: 'Hollywood',
    watchonline: encryptUrl('https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'),
    downloadlink: encryptDownloadObject(sampleVideoLinks.movie1),
    status: 'Publish',
  },
  {
    title: 'Spider-Man: Across the Spider-Verse',
    slug: 'spider-man-across-the-spider-verse',
    bgposter: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=1600&auto=format&fit=crop',
    smposter: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=600&auto=format&fit=crop',
    titlecategory: 'Movies',
    description: 'Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.',
    rating: '8.7',
    duration: '2h 20m',
    year: '2023',
    genre: ['Animation', 'Action', 'Adventure'],
    language: 'English',
    subtitle: 'English Subtitles',
    size: '2.4 GB',
    quality: '1080p Web-DL',
    youtubelink: 'https://www.youtube.com/watch?v=cqGjhVJWtEg',
    category: 'Marvel_Studio',
    watchonline: encryptUrl('https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4'),
    downloadlink: encryptDownloadObject(sampleVideoLinks.movie2),
    status: 'Publish',
  },
  {
    title: 'Oppenheimer',
    slug: 'oppenheimer-2023',
    bgposter: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?q=80&w=1600&auto=format&fit=crop',
    smposter: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?q=80&w=600&auto=format&fit=crop',
    titlecategory: 'Movies',
    description: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.',
    rating: '8.9',
    duration: '3h 00m',
    year: '2023',
    genre: ['Drama', 'Biography', 'History'],
    language: 'English',
    subtitle: 'English Subtitles',
    size: '3.1 GB',
    quality: '1080p BluRay',
    youtubelink: 'https://www.youtube.com/watch?v=uYPbbksJxIg',
    category: 'Hollywood',
    watchonline: encryptUrl('https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4'),
    downloadlink: encryptDownloadObject(sampleVideoLinks.movie3),
    status: 'Publish',
  },
  {
    title: 'Interstellar',
    slug: 'interstellar-2014',
    bgposter: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=1600&auto=format&fit=crop',
    smposter: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=600&auto=format&fit=crop',
    titlecategory: 'Movies',
    description: 'When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft through a wormhole.',
    rating: '8.7',
    duration: '2h 49m',
    year: '2014',
    genre: ['Science_Fiction', 'Adventure', 'Drama'],
    language: 'English',
    subtitle: 'English Subtitles',
    size: '2.6 GB',
    quality: '1080p BluRay',
    youtubelink: 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
    category: 'Hollywood',
    watchonline: encryptUrl('https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4'),
    downloadlink: encryptDownloadObject(sampleVideoLinks.movie1),
    status: 'Publish',
  },
  {
    title: 'Stranger Things (Season 4)',
    slug: 'stranger-things-season-4',
    bgposter: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1600&auto=format&fit=crop',
    smposter: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=600&auto=format&fit=crop',
    titlecategory: 'Series',
    description: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.',
    rating: '8.7',
    duration: '9 Episodes',
    year: '2022',
    genre: ['Horror', 'Science_Fiction', 'Drama'],
    language: 'English',
    subtitle: 'English Subtitles',
    size: '8.5 GB Complete',
    quality: '1080p Web-DL',
    youtubelink: 'https://www.youtube.com/watch?v=yQEondgpld0',
    category: 'TV_Shows',
    watchonline: encryptUrl('https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'),
    zipDownloadLink: encryptDownloadObject({
      '720p': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
      '1080p': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    }),
    episodes: [
      {
        episodeNumber: 'Ep 01',
        title: 'Chapter One: The Hellfire Club',
        downloadlink: encryptDownloadObject({
          '720p': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
          '1080p': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
        }),
      },
      {
        episodeNumber: 'Ep 02',
        title: "Chapter Two: Vecna's Curse",
        downloadlink: encryptDownloadObject({
          '720p': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoywatches.mp4',
          '1080p': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
        }),
      },
      {
        episodeNumber: 'Ep 03',
        title: 'Chapter Three: The Monster and the Superhero',
        downloadlink: encryptDownloadObject({
          '720p': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
          '1080p': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
        }),
      },
      {
        episodeNumber: 'Ep 04',
        title: 'Chapter Four: Dear Billy',
        downloadlink: encryptDownloadObject({
          '720p': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
          '1080p': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
        }),
      },
    ],
    status: 'Publish',
  },
  {
    title: 'The Dark Knight',
    slug: 'the-dark-knight-2008',
    bgposter: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=1600&auto=format&fit=crop',
    smposter: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=600&auto=format&fit=crop',
    titlecategory: 'Movies',
    description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    rating: '9.0',
    duration: '2h 32m',
    year: '2008',
    genre: ['Action', 'Crime', 'Drama'],
    language: 'English',
    subtitle: 'English Subtitles',
    size: '2.5 GB',
    quality: '1080p BluRay',
    youtubelink: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
    category: 'Hollywood',
    watchonline: encryptUrl('https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4'),
    downloadlink: encryptDownloadObject(sampleVideoLinks.movie2),
    status: 'Publish',
  },
  {
    title: 'RRR',
    slug: 'rrr-2022',
    bgposter: 'https://images.unsplash.com/photo-1533488765986-dfa2a9939acd?q=80&w=1600&auto=format&fit=crop',
    smposter: 'https://images.unsplash.com/photo-1533488765986-dfa2a9939acd?q=80&w=600&auto=format&fit=crop',
    titlecategory: 'Movies',
    description: 'A fictitious story about two legendary revolutionaries and their journey away from home before they started fighting for their country in the 1920s.',
    rating: '7.8',
    duration: '3h 07m',
    year: '2022',
    genre: ['Action', 'Drama', 'Adventure'],
    language: 'Telugu / Hindi',
    subtitle: 'English Subtitles',
    size: '3.2 GB',
    quality: '1080p Web-DL',
    youtubelink: 'https://www.youtube.com/watch?v=NgBoT01qQZ4',
    category: 'South',
    watchonline: encryptUrl('https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'),
    downloadlink: encryptDownloadObject(sampleVideoLinks.movie3),
    status: 'Publish',
  },
  {
    title: 'Jawan',
    slug: 'jawan-2023',
    bgposter: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?q=80&w=1600&auto=format&fit=crop',
    smposter: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?q=80&w=600&auto=format&fit=crop',
    titlecategory: 'Movies',
    description: 'A high-octane action thriller which outlines the emotional journey of a man who is set to rectify the wrongs in the society.',
    rating: '7.0',
    duration: '2h 49m',
    year: '2023',
    genre: ['Action', 'Thriller'],
    language: 'Hindi',
    subtitle: 'English Subtitles',
    size: '2.7 GB',
    quality: '1080p Web-DL',
    youtubelink: 'https://www.youtube.com/watch?v=MWOLN17xXYw',
    category: 'Bollywood',
    watchonline: encryptUrl('https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4'),
    downloadlink: encryptDownloadObject(sampleVideoLinks.movie1),
    status: 'Publish',
  },
  {
    title: 'Attack on Titan (Final Season)',
    slug: 'attack-on-titan-final-season',
    bgposter: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=1600&auto=format&fit=crop',
    smposter: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=600&auto=format&fit=crop',
    titlecategory: 'Anime',
    description: 'After his hometown is destroyed and his mother is killed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans.',
    rating: '9.1',
    duration: '28 Episodes',
    year: '2023',
    genre: ['Animation', 'Action', 'Fantasy'],
    language: 'Japanese',
    subtitle: 'English Subtitles',
    size: '6.4 GB',
    quality: '1080p Web-DL',
    youtubelink: 'https://www.youtube.com/watch?v=M_OauHnAFc8',
    category: 'anime',
    watchonline: encryptUrl('https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4'),
    zipDownloadLink: encryptDownloadObject({
      '720p': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoywatches.mp4',
      '1080p': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    }),
    episodes: [
      {
        episodeNumber: 'Ep 01',
        title: 'The Other Side of the Sea',
        downloadlink: encryptDownloadObject({
          '720p': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
          '1080p': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
        }),
      },
      {
        episodeNumber: 'Ep 02',
        title: 'Midnight Train',
        downloadlink: encryptDownloadObject({
          '720p': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoywatches.mp4',
          '1080p': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
        }),
      },
    ],
    status: 'Publish',
  },
  {
    title: 'Breaking Bad',
    slug: 'breaking-bad-complete',
    bgposter: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=1600&auto=format&fit=crop',
    smposter: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=600&auto=format&fit=crop',
    titlecategory: 'Series',
    description: 'A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing methamphetamine.',
    rating: '9.5',
    duration: '5 Seasons',
    year: '2013',
    genre: ['Crime', 'Drama', 'Thriller'],
    language: 'English',
    subtitle: 'English Subtitles',
    size: '18 GB',
    quality: '1080p BluRay',
    youtubelink: 'https://www.youtube.com/watch?v=HhesaQXLuRY',
    category: 'Web_Series',
    watchonline: encryptUrl('https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4'),
    zipDownloadLink: encryptDownloadObject({
      '720p': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
      '1080p': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    }),
    episodes: [
      {
        episodeNumber: 'Ep 01',
        title: 'Pilot',
        downloadlink: encryptDownloadObject({
          '720p': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
          '1080p': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
        }),
      },
      {
        episodeNumber: 'Ep 02',
        title: "Cat's in the Bag...",
        downloadlink: encryptDownloadObject({
          '720p': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
          '1080p': 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoywatches.mp4',
        }),
      },
    ],
    status: 'Publish',
  },
  {
    title: 'K.G.F: Chapter 2',
    slug: 'kgf-chapter-2',
    bgposter: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?q=80&w=1600&auto=format&fit=crop',
    smposter: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?q=80&w=600&auto=format&fit=crop',
    titlecategory: 'Movies',
    description: 'In the blood-soaked Kolar Gold Fields, Rocky’s name strikes fear into his foes.',
    rating: '8.3',
    duration: '2h 48m',
    year: '2022',
    genre: ['Action', 'Crime'],
    language: 'Kannada / Hindi',
    subtitle: 'English Subtitles',
    size: '2.9 GB',
    quality: '1080p Web-DL',
    youtubelink: 'https://www.youtube.com/watch?v=JKa05nyUmuQ',
    category: 'South',
    watchonline: encryptUrl('https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'),
    downloadlink: encryptDownloadObject(sampleVideoLinks.movie2),
    status: 'Publish',
  },
  {
    title: 'Demon Slayer: Kimetsu no Yaiba',
    slug: 'demon-slayer-kimetsu-no-yaiba',
    bgposter: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=1600&auto=format&fit=crop',
    smposter: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=600&auto=format&fit=crop',
    titlecategory: 'Anime',
    description: 'A family is attacked by demons and only two members survive - Tanjiro and his sister Nezuko.',
    rating: '8.6',
    duration: '3 Seasons',
    year: '2023',
    genre: ['Animation', 'Action', 'Fantasy'],
    language: 'Japanese',
    subtitle: 'English Subtitles',
    size: '7.2 GB',
    quality: '1080p Web-DL',
    youtubelink: 'https://www.youtube.com/watch?v=VQGCKyvzIM4',
    category: 'anime',
    watchonline: encryptUrl('https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4'),
    downloadlink: encryptDownloadObject(sampleVideoLinks.movie3),
    status: 'Publish',
  },
];

async function seedDB() {
  try {
    await connectDB();
    console.log('Clearing existing movies collection...');
    await Movie.deleteMany({});
    console.log('Inserting realistic encrypted seed movies data...');
    const inserted = await Movie.insertMany(mockMovies);
    console.log(`Successfully seeded ${inserted.length} movies with real media links into database!`);
    process.exit(0);
  } catch (error) {
    console.error('Failed to seed database:', error);
    process.exit(1);
  }
}

seedDB();
