import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Movie from './models/Post.js';
import connectDB from './libs/db.js';

dotenv.config();

const mockMovies = [
  {
    title: 'Dune: Part Two',
    slug: 'dune-part-two-2024',
    bgposter: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1600&auto=format&fit=crop',
    smposter: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=600&auto=format&fit=crop',
    titlecategory: 'Movies',
    description: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
    rating: '8.6',
    duration: '2h 46m',
    year: '2024',
    genre: ['Action', 'Science_Fiction', 'Adventure'],
    language: 'English',
    subtitle: 'English / Bengali Subtitles',
    size: '2.8 GB',
    quality: '4K Ultra HD',
    youtubelink: 'https://www.youtube.com/watch?v=Way9Dexny3w',
    category: 'Hollywood',
    watchonline: 'https://example.com/watch/dune-2',
    downloadlink: {
      '720p': 'https://example.com/download/dune2-720p',
      '1080p': 'https://example.com/download/dune2-1080p',
      '4k': 'https://example.com/download/dune2-4k',
    },
    status: 'Publish',
  },
  {
    title: 'Spider-Man: Across the Spider-Verse',
    slug: 'spider-man-across-the-spider-verse',
    bgposter: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=1600&auto=format&fit=crop',
    smposter: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=600&auto=format&fit=crop',
    titlecategory: 'Movies',
    description: 'Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.',
    rating: '8.7',
    duration: '2h 20m',
    year: '2023',
    genre: ['Animation', 'Action', 'Adventure'],
    language: 'English',
    subtitle: 'English Subtitles',
    size: '2.4 GB',
    quality: '1080p Web-DL',
    youtubelink: 'https://www.youtube.com/watch?v=cqGjhVJWtEg',
    category: 'Marvel_Studio',
    watchonline: 'https://example.com/watch/spider-verse',
    downloadlink: {
      '720p': 'https://example.com/download/spiderman-720p',
      '1080p': 'https://example.com/download/spiderman-1080p',
    },
    status: 'Publish',
  },
  {
    title: 'Oppenheimer',
    slug: 'oppenheimer-2023',
    bgposter: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?q=80&w=1600&auto=format&fit=crop',
    smposter: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?q=80&w=600&auto=format&fit=crop',
    titlecategory: 'Movies',
    description: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.',
    rating: '8.9',
    duration: '3h 00m',
    year: '2023',
    genre: ['Drama', 'Biography', 'History'],
    language: 'English',
    subtitle: 'English Subtitles',
    size: '3.1 GB',
    quality: '1080p BluRay',
    youtubelink: 'https://www.youtube.com/watch?v=uYPbbksJxIg',
    category: 'Hollywood',
    watchonline: 'https://example.com/watch/oppenheimer',
    downloadlink: {
      '720p': 'https://example.com/download/oppenheimer-720p',
      '1080p': 'https://example.com/download/oppenheimer-1080p',
    },
    status: 'Publish',
  },
  {
    title: 'Interstellar',
    slug: 'interstellar-2014',
    bgposter: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=1600&auto=format&fit=crop',
    smposter: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=600&auto=format&fit=crop',
    titlecategory: 'Movies',
    description: 'When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft through a wormhole.',
    rating: '8.7',
    duration: '2h 49m',
    year: '2014',
    genre: ['Science_Fiction', 'Adventure', 'Drama'],
    language: 'English',
    subtitle: 'English Subtitles',
    size: '2.6 GB',
    quality: '1080p BluRay',
    youtubelink: 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
    category: 'Hollywood',
    watchonline: 'https://example.com/watch/interstellar',
    downloadlink: {
      '720p': 'https://example.com/download/interstellar-720p',
      '1080p': 'https://example.com/download/interstellar-1080p',
    },
    status: 'Publish',
  },
  {
    title: 'Stranger Things (Season 4)',
    slug: 'stranger-things-season-4',
    bgposter: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1600&auto=format&fit=crop',
    smposter: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=600&auto=format&fit=crop',
    titlecategory: 'Series',
    description: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.',
    rating: '8.7',
    duration: '9 Episodes',
    year: '2022',
    genre: ['Horror', 'Science_Fiction', 'Drama'],
    language: 'English',
    subtitle: 'English Subtitles',
    size: '8.5 GB Complete',
    quality: '1080p Web-DL',
    youtubelink: 'https://www.youtube.com/watch?v=yQEondgpld0',
    category: 'TV_Shows',
    watchonline: 'https://example.com/watch/stranger-things',
    downloadlink: {
      '720p': 'https://example.com/download/stranger-things-720p',
      '1080p': 'https://example.com/download/stranger-things-1080p',
    },
    status: 'Publish',
  },
  {
    title: 'The Dark Knight',
    slug: 'the-dark-knight-2008',
    bgposter: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=1600&auto=format&fit=crop',
    smposter: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=600&auto=format&fit=crop',
    titlecategory: 'Movies',
    description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    rating: '9.0',
    duration: '2h 32m',
    year: '2008',
    genre: ['Action', 'Crime', 'Drama'],
    language: 'English',
    subtitle: 'English Subtitles',
    size: '2.5 GB',
    quality: '1080p BluRay',
    youtubelink: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
    category: 'Hollywood',
    watchonline: 'https://example.com/watch/dark-knight',
    downloadlink: {
      '720p': 'https://example.com/download/darkknight-720p',
      '1080p': 'https://example.com/download/darkknight-1080p',
    },
    status: 'Publish',
  },
  {
    title: 'RRR',
    slug: 'rrr-2022',
    bgposter: 'https://images.unsplash.com/photo-1533488765986-dfa2a9939acd?q=80&w=1600&auto=format&fit=crop',
    smposter: 'https://images.unsplash.com/photo-1533488765986-dfa2a9939acd?q=80&w=600&auto=format&fit=crop',
    titlecategory: 'Movies',
    description: 'A fictitious story about two legendary revolutionaries and their journey away from home before they started fighting for their country in the 1920s.',
    rating: '7.8',
    duration: '3h 07m',
    year: '2022',
    genre: ['Action', 'Drama', 'Adventure'],
    language: 'Telugu / Hindi',
    subtitle: 'English Subtitles',
    size: '3.2 GB',
    quality: '1080p Web-DL',
    youtubelink: 'https://www.youtube.com/watch?v=NgBoT01qQZ4',
    category: 'South',
    watchonline: 'https://example.com/watch/rrr',
    downloadlink: {
      '720p': 'https://example.com/download/rrr-720p',
      '1080p': 'https://example.com/download/rrr-1080p',
    },
    status: 'Publish',
  },
  {
    title: 'Jawan',
    slug: 'jawan-2023',
    bgposter: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?q=80&w=1600&auto=format&fit=crop',
    smposter: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?q=80&w=600&auto=format&fit=crop',
    titlecategory: 'Movies',
    description: 'A high-octane action thriller which outlines the emotional journey of a man who is set to rectify the wrongs in the society.',
    rating: '7.0',
    duration: '2h 49m',
    year: '2023',
    genre: ['Action', 'Thriller'],
    language: 'Hindi',
    subtitle: 'English Subtitles',
    size: '2.7 GB',
    quality: '1080p Web-DL',
    youtubelink: 'https://www.youtube.com/watch?v=MWOLN17xXYw',
    category: 'Bollywood',
    watchonline: 'https://example.com/watch/jawan',
    downloadlink: {
      '720p': 'https://example.com/download/jawan-720p',
      '1080p': 'https://example.com/download/jawan-1080p',
    },
    status: 'Publish',
  },
  {
    title: 'Attack on Titan (Final Season)',
    slug: 'attack-on-titan-final-season',
    bgposter: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=1600&auto=format&fit=crop',
    smposter: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=600&auto=format&fit=crop',
    titlecategory: 'Anime',
    description: 'After his hometown is destroyed and his mother is killed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction.',
    rating: '9.1',
    duration: '28 Episodes',
    year: '2023',
    genre: ['Animation', 'Action', 'Fantasy'],
    language: 'Japanese',
    subtitle: 'English Subtitles',
    size: '6.4 GB',
    quality: '1080p Web-DL',
    youtubelink: 'https://www.youtube.com/watch?v=M_OauHnAFc8',
    category: 'anime',
    watchonline: 'https://example.com/watch/aot',
    downloadlink: {
      '720p': 'https://example.com/download/aot-720p',
      '1080p': 'https://example.com/download/aot-1080p',
    },
    status: 'Publish',
  },
  {
    title: 'Breaking Bad',
    slug: 'breaking-bad-complete',
    bgposter: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=1600&auto=format&fit=crop',
    smposter: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=600&auto=format&fit=crop',
    titlecategory: 'Series',
    description: 'A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student in order to secure his family’s financial future.',
    rating: '9.5',
    duration: '5 Seasons',
    year: '2013',
    genre: ['Crime', 'Drama', 'Thriller'],
    language: 'English',
    subtitle: 'English Subtitles',
    size: '18 GB',
    quality: '1080p BluRay',
    youtubelink: 'https://www.youtube.com/watch?v=HhesaQXLuRY',
    category: 'Web_Series',
    watchonline: 'https://example.com/watch/breaking-bad',
    downloadlink: {
      '720p': 'https://example.com/download/breakingbad-720p',
      '1080p': 'https://example.com/download/breakingbad-1080p',
    },
    status: 'Publish',
  },
  {
    title: 'K.G.F: Chapter 2',
    slug: 'kgf-chapter-2',
    bgposter: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?q=80&w=1600&auto=format&fit=crop',
    smposter: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?q=80&w=600&auto=format&fit=crop',
    titlecategory: 'Movies',
    description: 'In the blood-soaked Kolar Gold Fields, Rocky’s name strikes fear into his foes. While his allies look up to him, the government sees him as a threat to law and order.',
    rating: '8.3',
    duration: '2h 48m',
    year: '2022',
    genre: ['Action', 'Crime'],
    language: 'Kannada / Hindi',
    subtitle: 'English Subtitles',
    size: '2.9 GB',
    quality: '1080p Web-DL',
    youtubelink: 'https://www.youtube.com/watch?v=JKa05nyUmuQ',
    category: 'South',
    watchonline: 'https://example.com/watch/kgf2',
    downloadlink: {
      '720p': 'https://example.com/download/kgf2-720p',
      '1080p': 'https://example.com/download/kgf2-1080p',
    },
    status: 'Publish',
  },
  {
    title: 'Demon Slayer: Kimetsu no Yaiba',
    slug: 'demon-slayer-kimetsu-no-yaiba',
    bgposter: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=1600&auto=format&fit=crop',
    smposter: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=600&auto=format&fit=crop',
    titlecategory: 'Anime',
    description: 'A family is attacked by demons and only two members survive - Tanjiro and his sister Nezuko, who is turning into a demon herself. Tanjiro sets out to become a demon slayer to avenge his family and cure his sister.',
    rating: '8.6',
    duration: '3 Seasons',
    year: '2023',
    genre: ['Animation', 'Action', 'Fantasy'],
    language: 'Japanese',
    subtitle: 'English Subtitles',
    size: '7.2 GB',
    quality: '1080p Web-DL',
    youtubelink: 'https://www.youtube.com/watch?v=VQGCKyvzIM4',
    category: 'anime',
    watchonline: 'https://example.com/watch/demon-slayer',
    downloadlink: {
      '720p': 'https://example.com/download/demonslayer-720p',
      '1080p': 'https://example.com/download/demonslayer-1080p',
    },
    status: 'Publish',
  },
];

async function seedDB() {
  try {
    await connectDB();
    console.log('Clearing existing movies collection...');
    await Movie.deleteMany({});
    console.log('Inserting mock movies data...');
    const inserted = await Movie.insertMany(mockMovies);
    console.log(`Successfully seeded ${inserted.length} movies into database!`);
    process.exit(0);
  } catch (error) {
    console.error('Failed to seed database:', error);
    process.exit(1);
  }
}

seedDB();
